### PR TITLE
Updated Russian language translation repo link

### PR DESCRIPTION
**Pull request by lufog**
Unfortunately, the old Russian translation is pretty outdated. Therefore, some time ago I started own translation.

### CODE REVIEW

**Comment by lufog** [comment]
@dacap please look at it.

**Comment by lufog** [comment]
@dacap, please look at it.

**Comment by dacap** [comment]
Hi @lufog, I'll take a look to this today at night.

**Comment by lufog** [comment]
@dacap so, will you merge it?

**Comment by dacap** [comment]
Hi @lufog, thanks for your patience, I've just merged [your change](https://github.com/aseprite/languages/commit/b7c23f53cc866ead427a8db7a88a371388cafc8f) into `main`. Thanks for sharing your updated Russian translation 🙏

**Pull request closed without merging**
